apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-pv
  labels:
    io.kompose.service: db-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/db
