apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: userservice
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userservice
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\system32\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: userservice
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: users_db
            - name: POSTGRES_HOST
              value: database
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_HEARTBEAT
              value: "120"
            - name: RABBITMQ_HOST
              value: rabbitmq.default.svc.cluster.local
            - name: RABBITMQ_PORT
              value: "5672"
          image: tomgibson1/userservice:v1
          name: userservice
          ports:
            - containerPort: 5002
              protocol: TCP
      restartPolicy: Always
